// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type VendorReview struct {
	ReviewID     string
	VendorID     string
	VendorName   string
	Poster       string
	Date         string
	Rating       int32
	Source       string
	Content      string
	LinkToSource string
}

type VendorReviewImage struct {
	ReviewID string
	ImageUrl string
}
