// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: vendor_review_image.sql

package database

import (
	"context"
)

const getImagesByReviewId = `-- name: GetImagesByReviewId :many
SELECT review_id, image_url FROM vendor_review_image
WHERE review_id = ?
`

func (q *Queries) GetImagesByReviewId(ctx context.Context, reviewID string) ([]VendorReviewImage, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByReviewId, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorReviewImage
	for rows.Next() {
		var i VendorReviewImage
		if err := rows.Scan(&i.ReviewID, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
